export const data: any[] = [
  {
    id: 0,
    imageUrl: "pots.png",
    description:
      "서버 개발자가 2명 있고 클라이언트 페이지 프론트엔드 개발 했습니다.",
    name: "EMS 통합 모니터링 홈페이지",
    skills:
      "React, React-Query, Typescript, Styled-Component, Recoil, StompJS, React-Simple-Tree-Menu",
    period: "2022.11 ~ ",
    developers: "1명 (client: 1명, server: 2명)",
    features:
      "트리 메뉴, 디자인 시스템, 실시간 데이터 통신, 차트, 목록 생성, 수정, 삭제",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2023,
  },
  {
    id: 1,
    imageUrl: "ipageonv3.png",
    description:
      "서버 개발자가 2명 있고 클라이언트 페이지 프론트엔드 개발 했습니다.",
    name: "EMS 모니터링 홈페이지",
    skills: "React, React-Query, Typescript, Styled-Component, Recoil, StompJS",
    period: "2022.11 ~ ",
    developers: "1명 (client: 1명, server: 2명)",
    features: "디자인 시스템, 실시간 데이터 통신, 차트, 목록 생성, 수정, 삭제",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2023,
  },
  {
    id: 2,
    imageUrl: "jebsv3.png",
    description:
      "서버 개발자가 1명 있고 반응형 클라이언트 페이지 프론트엔드 개발 했습니다.",
    name: "영어 교육 서비스 홈페이지",
    skills: "React, Next-JS, URQL, Typescript, XStyled, Matine",
    period: "2022.08 ~ 2022.10",
    developers: "1명 (client: 1명, server: 1명)",
    features:
      "디자인 시스템, 로그인, 회원가입, 마이페이지, 코스 구매, SHOP, 내 학습, 클래스",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2022,
  },
  {
    id: 3,
    imageUrl: "market_clientv3.png",
    description:
      "서버 개발자가 1명 있고 반응형 클라이언트 페이지 프론트엔드 개발 했습니다.",
    name: "NFT 마켓 플레이스 사이트",
    skills:
      "Next-JS, React-Query, Typescript, React-Admin, EmotionJS, React-Hook-Form, Material-UI",
    period: "2022.05 ~ 2022.07",
    developers: "1명 (client: 1명, server: 1명)",
    features:
      "메타마스크 로그인, 메타마스크 로그아웃, 작품 목록, 작품 검색, 작품 정렬, 작품 상세, 작품 구매, 작품 민팅, 작품 철회, 작품 신고, 작가 목록, 작가 신청, 작가 상세, 내 지갑 정보, 내 공지 목록",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2022,
  },
  {
    id: 4,
    imageUrl: "market_admin_v3.png",
    description:
      "서버 개발자가 1명 있고 관리자 페이지 프론트엔드 개발 했습니다.",
    name: "NFT 마켓 플레이스 관리자 페이지",
    skills: "React-Admin, EmotionJS, Material-UI",
    period: "2022.05 ~ 2022.06",
    developers: "1명 (client: 1명, server: 1명)",
    features:
      "대시보드, 작가 신청 목록, 유저 목록, 작품 목록, 공지사항 목록, 신고 목록, 관리자 목록",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2022,
  },
  {
    id: 5,
    imageUrl: "peachyv3.png",
    description:
      "강사들이 회원의 예약, 구매, 일정들을 관리 할 수 있는 플랫폼입니다.",
    name: "필라테스 회원 관리 솔루션 플랫폼",
    skills: "React, React-Query, Typescript, Grommet",
    period: "2021.12 ~ 2022.04",
    developers: "5명 (client: 3명, server: 2명)",
    features: "이벤트 상품 등록, 기타 매출 관리, 직원 관리",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2022,
  },
  {
    id: 6,
    imageUrl: "chattingv3.png",
    description:
      "SLACK 같은 기능을 만들고 있습니다. 현재는 개발 홀딩 상태입니다.",
    name: "채팅 사이드 프로젝트",
    skills:
      "React, SWR, Typescript, Emotionjs, Material-UI, Socket.IO, React-Hook-Form",
    period: "2021.10 ~ (현재 작업 홀딩)",
    developers: "1명 (client: 1명)",
    features: "회원가입, 로그인, 채팅방 개설, 그룹 채팅, Direct Message",
    githubUrl: "https://github.com/agger89/chatt",
    projectType: "SIDE_PROJECT",
    position: "FRONT_END",
    createdAt: 2021,
  },
  {
    id: 7,
    imageUrl: "react_adminv3.png",
    description:
      "기존 장고로 되어있는 관리자 페이지 migration 과 신규 관리자 페이지 클라이언트 개발을 담당 했습니다.",
    name: "자사 신규 관리자 페이지",
    skills:
      "React, Apollo-Client, Typescript, Material-UI, GraphQL Code Generator",
    period: "2019.08 ~ 2021.11",
    developers: "4명 (client: 2명, server: 2명)",
    features: "기존 관리자 기능 리뉴얼 (Django -> React-Admin)",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2021,
  },
  {
    id: 8,
    imageUrl: "testv3.png",
    description:
      "실제 직무적성검사 대비 온라인 모의고사 기능을 개발 했습니다. 문제와 답 등록은 어드민에서 구현해서 클라이언트와 연동 했습니다.",
    name: "실제 직무적성검사 대비 온라인 모의고사 서비스",
    skills:
      "React, Apollo-Client, Typescript, Material-UI, GraphQL Code Generator, React-Hook-Form",
    period: "2021.06 (약 3주 소요)",
    developers: "3명 (client: 2명, server: 1명)",
    features:
      "온라인 모의고사 시험 기능 관리자 페이지 개발 (문제 생성, 문제 수정, 문제 삭제), 유저 화면단 개발 (문제 풀기, 정답 제출, 답안지)",
    githubUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2021,
  },
  {
    id: 9,
    imageUrl: "diaryv3.png",
    description:
      "서버 개발자와 같이 사이드 프로젝트로 익명 다이어리 기능을 만들고 있습니다. 현재는 개발 홀딩 상태입니다.",
    name: "익명 다이어리 웹",
    skills:
      "React, Apollo-Client, Typescript, Styled Components, GraphQL Code Generator",
    period: "2021.10 ~ (현재 작업 홀딩)",
    developers: "2명 (client: 1명, server: 1명)",
    features:
      "게시글 보여주기, 게시글 작성, 게시글 좋아요, 게시글 댓글 등록, 삭제",
    githubUrl: "https://github.com/agger89/diary",
    projectType: "SIDE_PROJECT",
    position: "FRONT_END",
    createdAt: 2021,
  },
  {
    id: 10,
    imageUrl: "user_leavev3.png",
    description: "자사 사이트의 회원 탈퇴 기능을 리뉴얼 했습니다.",
    name: "일반회원, SNS회원 탈퇴",
    skills:
      "Apollo-Client, Typescript, React-Hook-Form, GraphQL Code Generator, Material-UI",
    period: "2021.02 (약 2주 소요)",
    developers: "2명 (client: 1명, server: 1명)",
    features:
      "일반 회원 탈퇴 처리 (탈퇴 사유, 비밀번호 입력 후 validation 체크 후 탈퇴 처리), SNS 회원 탈퇴 처리 (핸드폰 번호 인증 확인 후 탈퇴 처리)",
    webSiteUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2021,
  },
  {
    id: 11,
    imageUrl: "freepass_timerv3.png",
    description:
      "유저에게 수강신청 마감일자와 기수를 보여주는 타이머 기능입니다.",
    name: "수강신청 타이머",
    skills:
      "React-Admin, Apollo-Client, Typescript, GraphQL Code Generator, Material-UI",
    period: "2020.11 ~ 2020.12",
    developers: "2명 (client: 1명, server: 1명)",
    features:
      "컨텐츠 강의 수강신청 기능 관리자 페이지 개발 (기수, 신청 마감 날짜), 유저 화면단 개발 (타이머)",
    webSiteUrl:
      "https://next.weport.co.kr/freepass/timer-banner/weport-main-top-banner",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2020,
  },
  {
    id: 12,
    imageUrl: "tree_menuv3.png",
    description:
      "관리자 페이지에서 사이트 네비게이션 메뉴를 유연하게 추가, 삭제, 이동 할 수 있는 기능입니다.",
    name: "트리 메뉴",
    skills: "react-sortable-tree",
    period: "2020.01 (약 2주 소요)",
    developers: "1명 (client: 1명)",
    features: "메뉴 순서 변경(drag n drop), 자식 메뉴 추가, 삭제",
    githubUrl: "https://github.com/agger89/sortable-tree",
    webSiteUrl: "https://sortable-tree.vercel.app",
    projectType: "SIDE_PROJECT",
    position: "FRONT_END",
    createdAt: 2020,
  },
  {
    id: 13,
    imageUrl: "parse_excelv3.png",
    description: "액셀을 불러온 후 row 데이터로 파싱해주는 기능입니다.",
    name: "액셀 데이터 파싱",
    skills: "xlsx, react-dropzone",
    period: "2020.02 (약 1주 소요)",
    developers: "1명 (client: 1명)",
    features: "액셀의 값들 불러온 후 row 형태의 데이터로 parsing",
    githubUrl: "https://github.com/agger89/parse-excel",
    webSiteUrl: "https://parse-excel.vercel.app",
    projectType: "SIDE_PROJECT",
    position: "FRONT_END",
    createdAt: 2020,
  },
  {
    id: 14,
    imageUrl: "pass_checkv3.jpg",
    description:
      "자사의 서비스 교재를 등록 및 선택 할 수 있는 팝업 기능입니다.",
    name: "교재 등록 및 선택 팝업",
    skills:
      "Next.js, React-Admin, Apollo-Client, Typescript, GraphQL Code Generator, Material-UI, react-beautiful-dnd",
    period: "2020.02 ~ 2020.03",
    developers: "2명 (client: 1명, server: 1명)",
    features:
      "교재 등록 기능 관리자 페이지 개발 (교재 생성, 교재 수정, 교재 삭제, 교재 순서 변경), 유저 화면단 구현 (교재 선택 팝업)",
    webSiteUrl: "http://next.weport.co.kr/pass-check",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2020,
  },
  {
    id: 15,
    imageUrl: "nextjs_portfoliov3.png",
    description: "인프런 강의영상을 보며 클론 코딩한 twitter 홈페이지입니다.",
    name: "twitter 클론 코딩",
    skills:
      "NextJS(SSR), Redux, Redux-Saga, Styled Components, AntDesign, Node, Express, Sequelize(MySQL)",
    period: "2019",
    developers: "1명",
    features:
      "회원가입, 로그인, 로그아웃, 해시태그 검색, 리트윗, 팔로우, 언팔로우, 글 등록, 글 삭제, 댓글 등록, 좋아요, 이미지 업로드, 닉네임 변경, 이미지 슬라이드, 인피니트 스크롤링, 페이지네이션",
    webSiteUrl: "",
    githubUrl: "https://github.com/agger89/choWitter",
    projectType: "SIDE_PROJECT",
    position: "FRONT_END",
    createdAt: 2019,
  },
  {
    id: 16,
    imageUrl: "aipev3.png",
    description: "자사 소개 홈페이지입니다. (현재 서비스 중지)",
    name: "자사 소개 홈페이지",
    skills: "React, Styled-Components",
    period: "2019.02 ~ 2019.03",
    developers: "2명 (client: 1명, server: 1명)",
    features: "클라이언트 초기 구축(create-react-app) 및 개발",
    webSiteUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2019,
  },
  {
    id: 17,
    imageUrl: "3piksv3.png",
    description:
      "자사 ai 로봇이 코인의 상승,보함,하락을 예측하는 홈페이지입니다. (현재 서비스 중지)",
    name: "3piks",
    skills: "React, Styled-Components, React-Redux, Redux-Saga",
    period: "2018.10 ~ 2018.12",
    developers: "4명 (client: 2명, server: 2명)",
    features:
      "클라이언트 초기 세팅(create-react-app), 화면단 데이터 상태관리(React-Redux), API 비동기 데이터 연결(Redux-Saga)",
    webSiteUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "FRONT_END",
    createdAt: 2019,
  },
  {
    id: 18,
    imageUrl: "react_portfoliov3.png",
    description: "혼자 공부하려고 만든 Instagram 홈페이지입니다.",
    name: "Instagram 홈페이지",
    skills: "React, SCSS, React-Redux",
    period: "2018",
    developers: "1명 (client: 1명)",
    features: "팔로우, 언팔로우, 댓글 등록, 좋아요",
    webSiteUrl: "https://instareact-25862.firebaseapp.com",
    githubUrl: "https://github.com/agger89/portfolioREACT",
    projectType: "SIDE_PROJECT",
    position: "FRONT_END",
    createdAt: 2018,
  },
  {
    id: 19,
    imageUrl: "puffv3.png",
    description: "운영팀이 퀴즈쇼의 문제를 세팅하는 화면을 퍼블리싱 했습니다.",
    name: "라이브 퀴즈쇼",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2018.05 ~ 2018.06",
    developers: "1명 (client: 1명)",
    features: "문제 등록화면 퍼블리싱",
    webSiteUrl: "",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2018,
  },
  {
    id: 20,
    imageUrl: "php_portfoliov3.png",
    description: "공부하려고 만든 php 기반의 Instagram 홈페이지입니다.",
    name: "Instagram 홈페이지",
    skills: "HTML, SCSS, Javascript, jQuery, PHP, MySQL",
    period: "2018",
    developers: "1명 (client: 1명)",
    features:
      "회원가입, 로그인, 로그아웃, 팔로우, 언팔로우, 글 등록, 글 삭제, 댓글 등록, 댓글 삭제, 좋아요, 이미지 업로드, 프로필 변경, 유저 활동 실시간 알림",
    webSiteUrl: "",
    githubUrl: "https://github.com/agger89/portfolioPHP",
    projectType: "SIDE_PROJECT",
    position: "PUBLISHER",
    createdAt: 2018,
  },
  {
    id: 21,
    imageUrl: "travelmapv3.png",
    description:
      "전세계 호텔, 항공, 렌터카, 여행을 가격비교 할 수 있는 홈페이지입니다.",
    name: "TRAVELMAP",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2017.02 ~ 2017.04",
    developers: "3명 (client: 2명, server: 1명)",
    features: "퍼블리싱",
    webSiteUrl: "http://www.travelmap.co.kr",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2017,
  },
  {
    id: 22,
    imageUrl: "mobile_appliancev3.png",
    description: "자동차 솔루션 기업 소개 홈페이지입니다.",
    name: "Mobile Appliance",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2017.04 ~ 2017.06",
    developers: "3명 (client: 2명, server: 1명)",
    features: "퍼블리싱",
    webSiteUrl: "http://www.mobileappliance.co.kr",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2017,
  },
  {
    id: 23,
    imageUrl: "pontusv3.png",
    description: "블랙박스 소개 및 고객센터 홈페이지입니다.",
    name: "PONTUS",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2017.04 ~ 2017.06",
    developers: "3명 (client: 2명, server: 1명)",
    features: "퍼블리싱",
    webSiteUrl: "http://www.pontus.co.kr",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2017,
  },
  {
    id: 24,
    imageUrl: "sarahanv3.png",
    description: "화장품 소개 및 판매 홈페이지입니다. (현재 서비스 중지)",
    name: "Sarahan",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2017.06 ~ 2017.08",
    developers: "3명 (client: 2명, server: 1명)",
    features: "퍼블리싱",
    webSiteUrl: "http://www.sarahan.kr",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2017,
  },
  {
    id: 25,
    imageUrl: "dentalv3.png",
    description: "병원 병원소개 및 예약 사이트입니다.",
    name: "문치과병원",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2017.06 ~ 2017.08",
    developers: "3명 (client: 2명, server: 1명)",
    features: "퍼블리싱",
    webSiteUrl: "http://www.moondh.co.kr",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2017,
  },
  {
    id: 26,
    imageUrl: "kw_honeyv3.png",
    description: "벌꿀소개 및 판매 사이트입니다.",
    name: "자연에 쉼",
    skills: "HTML, CSS, JS, JQUERY",
    period: "2017.06 ~ 2017.08",
    developers: "3명 (client: 2명, server: 1명)",
    features: "퍼블리싱",
    webSiteUrl: "http://www.kwhoney.kr",
    projectType: "COMPANY_PROJECT",
    position: "PUBLISHER",
    createdAt: 2017,
  },
];
